/**
 * Central map of app screenshots → keyed by the place they appear. Imported as
 * ImageMetadata so `astro:assets` can emit optimized, responsive AVIF/WebP.
 * Source PNGs are frameless full-screen captures; they are wrapped in a CSS
 * device bezel by <PhoneFrame>.
 *
 * NOTE: these are branded PLACEHOLDERS generated by `scripts/make-placeholders.mjs`
 * until the real app screenshots arrive — just overwrite the PNGs in
 * `src/assets/screens/` with the real captures (same filenames) and rebuild.
 */
import home from '@/assets/screens/home.png';
import stations from '@/assets/screens/stations.png';
import amenities from '@/assets/screens/amenities.png';
import recitations from '@/assets/screens/recitations.png';
import competition from '@/assets/screens/competition.png';

export const SCREENS = {
  hero: home, // home screen
  stations, // stations list / a station with its adhkar (Showcase flagship)
  amenities, // roadside services on the map
  recitations, // audio ziyarat / du'a library
  competition, // a per-station quiz question
} as const;
